# Generated by Django 5.0.6 on 2024-07-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusmodels',
            options={'verbose_name_plural': 'Contact Us'},
        ),
    ]
